# Generated by Django 6.0.5 on 2026-06-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Unknown', max_length=10)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(null=True)),
                ('response_time', models.FloatField(null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.website')),
            ],
        ),
    ]
