# Generated by Django 6.0.5 on 2026-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Stopped', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('interval', models.CharField(default='Every 5 Hours', max_length=50)),
            ],
        ),
    ]
